// Design list
const projects = [
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "제주 흙더덕 상세페이지",
    thumb: "img/thumb1.jpg",
    detail: "img/detail1.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "수건 상세페이지",
    thumb: "img/thumb2.jpg",
    detail: "img/detail2.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "올리브오일 상세페이지",
    thumb: "img/thumb3.jpg",
    detail: "img/detail3.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "아카시아 스틱꿀 상세페이지",
    thumb: "img/thumb4.jpg",
    detail: "img/detail4.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "특선 건과5종 상세페이지",
    thumb: "img/thumb5.jpg",
    detail: "img/detail5.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "베리믹스앤넛 상세페이지",
    thumb: "img/thumb13.jpg",
    detail: "img/detail13.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "시나몬스틱 상세페이지",
    thumb: "img/thumb6.jpg",
    detail: "img/detail6.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "유자차 상세페이지",
    thumb: "img/thumb7.jpg",
    detail: "img/detail7.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "쌍화차재료 상세페이지",
    thumb: "img/thumb8.jpg",
    detail: "img/detail8.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "월계수잎 상세페이지",
    thumb: "img/thumb9.jpg",
    detail: "img/detail9.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "레몬밤티백 상세페이지",
    thumb: "img/thumb10.jpg",
    detail: "img/detail10.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "삼계탕재료 상세페이지",
    thumb: "img/thumb11.jpg",
    detail: "img/detail11.jpg",
  },
  {
    category: "detail",
    sub: "DETAIL PAGE",
    title: "밤고구마 상세페이지",
    thumb: "img/thumb12.jpg",
    detail: "img/detail12.jpg",
  },

  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster1.jpg",
    detail: "img/poster1-1.jpg",
  },
  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster2.jpg",
    detail: "img/poster2-1.jpg",
  },
  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster3.jpg",
    detail: "img/poster3-1.jpg",
  },
  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster4.jpg",
    detail: "img/poster4-1.jpg",
  },
  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster5.jpg",
    detail: "img/poster5-1.jpg",
  },
  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster6.jpg",
    detail: "img/poster6-1.jpg",
  },
  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster7.jpg",
    detail: "img/poster7-1.jpg",
  },
  {
    category: "poster",
    sub: "POSTER",
    title: "법무법인 포스터",
    thumb: "img/poster8.jpg",
    detail: "img/poster8-1.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "법무법인 배너",
    thumb: "img/banner1.jpg",
    detail: "img/banner1.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "법무법인 배너",
    thumb: "img/banner2.jpg",
    detail: "img/banner2.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "법무법인 배너",
    thumb: "img/banner3.jpg",
    detail: "img/banner3.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "법무법인 배너",
    thumb: "img/banner4.jpg",
    detail: "img/banner4.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "차량렌트 배너",
    thumb: "img/banner5.jpg",
    detail: "img/banner5.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "차량렌트 배너",
    thumb: "img/banner6.jpg",
    detail: "img/banner6.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "시계 쇼핑몰 배너",
    thumb: "img/banner7.jpg",
    detail: "img/banner7.jpg",
  },
  {
    category: "banner",
    sub: "BANNER",
    title: "시계 쇼핑몰 배너",
    thumb: "img/banner8.jpg",
    detail: "img/banner8-1.jpg",
  },
  {
    category: "etc",
    sub: "ETC.",
    title: "차량 구매 가이드",
    thumb: "img/etc1.jpg",
    detail: "img/etc1-1.jpg",
  },
  {
    category: "etc",
    sub: "ETC.",
    title: "메뉴판",
    thumb: "img/etc2.jpg",
    detail: "img/etc2-1.jpg",
  },
];
